# Generated by Django 6.0.5 on 2026-09-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_syllabusdrafttopic'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSession',
            new_name='CourseCalendar',
        ),
        migrations.AlterModelOptions(
            name='coursecalendar',
            options={'ordering': ['session_date', 'start_time'], 'verbose_name': 'Course Calendar', 'verbose_name_plural': 'Course Calendars'},
        ),
    ]
