# Generated by Django 6.0.5 on 2026-09-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_coursesession_to_coursecalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCalendarLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField(blank=True, help_text='Leave blank if it happened as scheduled', null=True)),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='What happened: delay reason, merge details, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendar_entries', models.ManyToManyField(related_name='logs', to='schedule.coursecalendar')),
            ],
            options={
                'verbose_name': 'Course Calendar Log',
                'verbose_name_plural': 'Course Calendar Logs',
                'db_table': 'schedule_coursecalendarlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
