# Generated by Django 6.0.5 on 2026-09-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_add_coursecalendarlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Non-Working Day',
                'verbose_name_plural': 'Non-Working Days',
                'db_table': 'schedule_nonworkingday',
                'ordering': ['date'],
            },
        ),
    ]
