# Generated by Django 6.0.5 on 2026-09-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_nonworkingday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecalendarlog',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='coursecalendarlog',
            name='actual_start_time',
        ),
        migrations.AddField(
            model_name='coursecalendarlog',
            name='problems',
            field=models.TextField(blank=True, help_text='Any problems encountered (optional)'),
        ),
        migrations.AddField(
            model_name='coursecalendarlog',
            name='solutions',
            field=models.TextField(blank=True, help_text='How problems were resolved (optional)'),
        ),
    ]
