# Generated by Django 6.0.5 on 2026-09-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_coursecalendarlog_actual_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecalendarlog',
            name='description',
        ),
    ]
