# Generated by Django 6.0.5 on 2026-09-29 13:55

import django.db.models.deletion
from django.db import migrations, models


def backfill_ideal_topics(apps, schema_editor):
    """Nth slot of each course -> Nth topic by order (mirrors courses.views._assign_ideal_topics)"""
    Course = apps.get_model('courses', 'Course')
    CourseCalendar = apps.get_model('schedule', 'CourseCalendar')
    for course in Course.objects.all():
        topics = list(course.topics.order_by('order'))
        sessions = CourseCalendar.objects.filter(course=course).order_by('session_date', 'start_time')
        for session, topic in zip(sessions, topics):
            session.ideal_topic = topic
            session.save(update_fields=['ideal_topic'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_syllabusdrafttopic'),
        ('schedule', '0006_remove_coursecalendarlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecalendar',
            name='ideal_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideal_sessions', to='courses.topic'),
        ),
        migrations.RunPython(backfill_ideal_topics, migrations.RunPython.noop),
    ]
