# Generated by Django 6.0.5 on 2026-05-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('assignature', 'name', 'period')},
        ),
    ]
