# Generated by Django 6.0.5 on 2026-05-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['course', 'start_time'], 'verbose_name': 'Course Schedule', 'verbose_name_plural': 'Course Schedules'},
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('course', 'start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='days',
            field=models.JSONField(default=list, help_text='List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday'),
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='day_of_week',
        ),
    ]
