# Generated by Django 6.0.5 on 2026-09-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_move_schedule_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusDraftTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_drafts', to='courses.course')),
            ],
            options={
                'verbose_name': 'Syllabus Draft Topic',
                'verbose_name_plural': 'Syllabus Draft Topics',
                'ordering': ['order'],
            },
        ),
    ]
